# Schema for the configuration files of the Site Location module.
site_location.settings:
  type: config_object
  label: 'Site Location settings'
  mapping:
    country:
      type: string
      label: 'Country'
    city:
      type: string
      label: 'City'
    timezone:
      type: string
      label: 'Timezone'
